//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexibleDBMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexibleDBMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------------------------------.
        /// </summary>
        internal static string DashedSymbols {
            get {
                return ResourceManager.GetString("DashedSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==================================== .
        /// </summary>
        internal static string EqualSymbols {
            get {
                return ResourceManager.GetString("EqualSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoRYIK {
            get {
                object obj = ResourceManager.GetObject("LogoRYIK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бэкап конфигурации (*.bak)|*.bak|Файл конфигурации (*.cfg)|*.cfg|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenDialogCfgFile {
            get {
                return ResourceManager.GetString("OpenDialogCfgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базы данных (*.db)|*.db|Текстовые файлы (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenDialogDbFile {
            get {
                return ResourceManager.GetString("OpenDialogDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel файлы (*.xls*)|*.xls*|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenDialogExcelFile {
            get {
                return ResourceManager.GetString("OpenDialogExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовые файлы (*.txt)|*.txt|Базы данных (*.db)|*.db|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenDialogTextFile {
            get {
                return ResourceManager.GetString("OpenDialogTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл обновления (*.zip)|*.zip|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenDialogZipFile {
            get {
                return ResourceManager.GetString("OpenDialogZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- / --- / --- / --- / --- / --- / --- / --- / --- / --- / --- / --- /.
        /// </summary>
        internal static string SosSlashSymbols {
            get {
                return ResourceManager.GetString("SosSlashSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- / --- / --- / --- / --- / --- / --- / --- / --- / --- / --- .
        /// </summary>
        internal static string SosSlashSymbolsBack {
            get {
                return ResourceManager.GetString("SosSlashSymbolsBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---.
        /// </summary>
        internal static string SosSymbols {
            get {
                return ResourceManager.GetString("SosSymbols", resourceCulture);
            }
        }
    }
}
